version: "3.7"

services:
  mysqldb:
    image: mysql:8.0.29
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: 'library_db_api'
    ports:
      - "3307:3306"
      - "33070:33060"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: library_db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      # - my-datavolume:/var/lib/mysql
      - ./sql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      
# volumes:
#   my-datavolume:



