spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3307/library_db
    username: root
    password: secret
  jpa:
    #hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true


server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never